### ISSUE TITLE
Explanation for Code.

### ISSUE THREAD

**Issue by ali-raza-iftikhar** [prafullbhosale/CustomScaffolder#1]
Hi Can you explain me the CustomeScaffolder.cs and SampleGeneratorModel.cs implementation. I will be very thankful to you.
And one more thing. The instructions you have provided for build and model creation run successfully but no model gets generated. :-)

**Comment by prafullbhosale** [comment]
Hi @ali-raza-iftikhar, the `CustomScaffolder` in this case doesn't actually do anything. 
This was intended to demonstrate how a custom scaffolder would get invoked by `dotnet-aspnet-codegenerator`.

 - The `CustomScaffolder.GenerateCode` method is the main entry point which gets invoked by the scaffolding engine. 

 - The `SampleGeneratorModel` defines the command line parameters that are accepted by the `CustomScaffolder`



> but no model gets generated

Yes, that was intentional, it was only intended to print the passed in model to the console. 

I have another sample https://github.com/prafullbhosale/EmptyControllerAndViewScaffolder
This repo has a working scaffolder that adds an empty controller and view in a single operation. 

https://github.com/prafullbhosale/EmptyControllerAndViewScaffolder/blob/master/EmptyControllerAndViewScaffolder/ControllerAndViewGenerator.cs

Let me know if this sample explains what you are looking for.

**Comment by ali-raza-iftikhar** [comment]
Thanks that was something i was looking for. :-)
